apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-wait-job"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: wait-container
        image: bash:5.0
        command: ['bash', '-c', 'sleep 30']
      restartPolicy: Never