apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mentor.deployment.name" . }}
  labels:
    {{- include "mentor.labels" . | nindent 4 }}
spec:
  replicas: {{ if and .Values.mentor .Values.mentor.replicaCount }}{{ .Values.mentor.replicaCount }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      {{- include "mentor.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mentor.labels" . | nindent 8 }}
    spec:
      containers:
        - name: merly-mentor
          image: {{ include "mentor.deployment.image"  . }}
          ports:
            - containerPort: {{ if and .Values.mentor .Values.mentor.containerPort }}{{ .Values.mentor.containerPort }}{{ else }}4200{{ end }}
          env:
            - name: REGISTRATION_KEY
              value: {{ if and .Values.global .Values.global.registrationKey -}}{{ .Values.global.registrationKey }}{{- else -}}{{ fail (print "A valid registration key is required! Ensure .Values.global.registrationKey is properly set.") }}{{ end }}
            {{- range $key, $value := .Values.mentor.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          args:
            {{- range .Values.mentor.arguments }}
            - {{ . | quote }}
            {{- end }}
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "16Gi"
              cpu: "12"
          volumeMounts:
            - mountPath: /app/.mentor
              name: mentor-data
            - mountPath: /app/.models
              name: models-data
            - mountPath: /app/.assets
              name: assets-data
            - mountPath: /app/.logs
              name: logs-data
            
              
        - name: bridge-container
          image: {{ include "bridge.deployment.image" . }}
          ports:
            - containerPort: {{ if and .Values.bridge .Values.bridge.containerPort }}{{ .Values.bridge.containerPort }}{{ else }}8080{{ end }}
          env:
            - name: MERLY_AI_DAEMON_URL
              value: "http://{{ include "mentor.service.name" . }}:{{ if and .Values.mentor .Values.mentor.service .Values.mentor.service.port }}{{ .Values.mentor.service.port }}{{ else }}4200{{ end }}/"
          volumeMounts:
            - mountPath: /app/.mentor
              name: mentor-data
            - mountPath: /app/.logs
              name: logs-data

      volumes:
        - name: mentor-data
          persistentVolumeClaim:
            claimName: {{ if and .Values.global .Values.global.persistence .Values.global.persistence.pvcNameOverride }}{{ .Values.global.persistence.pvcNameOverride }}{{ else }}merly-mentor-pvc{{ end }}
        - name: logs-data
          persistentVolumeClaim:
            claimName: {{ if and .Values.global .Values.global.logsPersistence .Values.global.logsPersistence.pvcNameOverride }}{{ .Values.global.logsPersistence.pvcNameOverride }}{{ else }}merly-logs-pvc{{ end }}
        - name: models-data
          emptyDir: {}
        - name: assets-data
          emptyDir: {}
