apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ if and .Values.global .Values.global.persistence .Values.global.persistence.pvcNameOverride }}{{ .Values.global.persistence.pvcNameOverride }}{{ else }}merly-mentor-pvc{{ end }}
spec:
  {{- if and .Values.global .Values.global.persistence .Values.global.persistence.storageClass }}
  storageClassName: {{ .Values.global.persistence.storageClass }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      {{- if and .Values.global .Values.global.persistence . .Values.global.persistence.size }}
      storage: {{ .Values.global.persistence.size }}
      {{- else }}
      storage: 4Gi
      {{- end }}