apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ if and .Values.global .Values.global.logsPersistence .Values.global.logsPersistence.pvcNameOverride }}{{ .Values.global.logsPersistence.pvcNameOverride }}{{ else }}merly-logs-pvc{{ end }}
spec:
  {{- if and .Values.global .Values.global.logsPersistence .Values.global.logsPersistence.storageClass }}
  storageClassName: {{ .Values.global.logsPersistence.storageClass }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {{- if and .Values.global .Values.global.logsPersistence . .Values.global.logsPersistence.size }}
      storage: {{ .Values.global.logsPersistence.size }}
      {{- else }}
      storage: 4Gi
      {{- end }}