apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ if and .Values.global .Values.global.persistence .Values.global.persistence.pvcNameOverride }}
    {{ .Values.global.persistence.pvcNameOverride }}
  {{ else }}
    merly-mentor-pvc
  {{ end }}
spec:
  {{- if or (eq .Values.global.kubernetesProvider "minikube") (eq .Values.global.kubernetesProvider "kind") }}
  storageClassName: nfs
  {{- else if and .Values.global .Values.global.persistence .Values.global.persistence.storageClass }}
  storageClassName: {{ .Values.global.persistence.storageClass }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ if and .Values.global .Values.global.persistence .Values.global.persistence.size }}
      {{ .Values.global.persistence.size }}
      {{ else }}
      4Gi
      {{ end }}
