name: Update Documentation
on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'
permissions: {}
jobs:
  build:
    permissions:
      contents: write # for git push

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
          github-corners: https://github.com/merly-ai/mentor-helm-chart
      - run: |
          cp -f index.html ${{ runner.temp }}/index.html
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - run: |
          cp -f ${{ runner.temp }}/index.html .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add index.html
          git commit --signoff -m "Sync README from main"
          git push
