name: Update Documentation
on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'
permissions: {}
jobs:
  build:
    permissions:
      contents: write # for git push

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
          github-corners: https://github.com/merly-ai/mentor-helm-chart
          favicon: https://www.merly.ai/favicon.ico
          title: "Merly Mentor Helm Chart"
          description: "Helm Chart for Merly Mentor"
          markdown-style-theme: light
          style: |
            body {
              font-family: Arial, sans-serif;
              margin: 20px;
            }
            h1 {
              color: #333;
            }
            h2 {
              color: #555;
            }
            h3 {
              color: #777;
            }
            p {
              color: #999;
            }
            a {
              color: #007bff;
            }
            a:hover {
              color: #0056b3;
            }
            pre {
              background-color: #f8f9fa;
              border: 1px solid #e9ecef;
              border-radius: 3px;
              padding: 10px;
            }
            code {
              background-color: #f8f9fa;
              border: 1px solid #e9ecef;
              border-radius: 3px;
              padding: 2px;
            }
            table {
              border-collapse: collapse;
              width: 100%;
            }
            th, td {
              border: 1px solid #ddd;
              padding: 8px;
              text-align: left;
            }
            th {
              background-color: #f2f2f2;
            }
            tr:nth-child(even) {
              background-color: #f2f2f2;
            }
            tr:hover {
              background-color: #f2f2f2;
            }
      - run: |
          cp -f index.html ${{ runner.temp }}/index.html
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - run: |
          cp -f ${{ runner.temp }}/index.html .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add index.html
          git commit --signoff -m "Sync README from main"
          git push
